
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.43.168:3306/software
    #    zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: abC123456!

#  data:
#    redis:
#      password: 123456
#      port: 6379
#      host: 8.130.43.168

  redis:
    host: 8.130.43.168
    port: 6379
    password: 123456
    database: 0


  mail:
    # 163??????smtp.163.com???????
    host: smtp.163.com
    protocol: smtps
    # 465?????SSL????????25??????SSL??????
    port: 465
    # ????163??
    username: ljz2020comeon@163.com
    # ????????smtp/pop3?????????????????????
    password: LOAVUNUAXCRCZDRA